### ISSUE TITLE
无法生成日志文件

### ISSUE THREAD

**Issue by FrankLove** [iflove/Logcat#5]
为什么无法生存日志文件

**Comment by iflove** [comment]
fileLogLevel 不能设置 ` fileLogLevel(Logcat.NOT_SHOW_LOG)`
`Logcat.v().file().msg("output file msg").out();`  or `Logcat.v("Mylog.txt").file().msg("output file msg").out();`
默认log文件夹 sdcard/Android/data/you.pakeage/cache/logs 下
