### ISSUE TITLE
open failed: EMFILE (Too many open files)

### ISSUE THREAD

**Issue by wuzhenzhen** [iflove/Logcat#9]
你好，出现了“java.io.FileNotFoundException: *.log: open failed: EMFILE (Too many open files)”

是不是打印日志太多了？

**Comment by iflove** [comment]
发生FileNotFoundException 的场景？

**Comment by wuzhenzhen** [comment]
@iflove   是的，并且是每隔一段时间都会遇到，

**Comment by iflove** [comment]
程序crash了?

**Comment by wuzhenzhen** [comment]
就是，软件退出了。
37305 D/Logcat  ( 7350): New FileWriter Instance failed
37306 W/System.err( 7350): java.io.FileNotFoundException: /sdcard/EBSB_SDCardLog/2018-07-20.log: open failed: EMFILE (Too many open files)
37307 W/System.err( 7350):     at libcore.io.IoBridge.open(IoBridge.java:409)
37308 W/System.err( 7350):     at java.io.FileOutputStream.<init>(FileOutputStream.java:88)
37309 W/System.err( 7350):     at java.io.FileWriter.<init>(FileWriter.java:58)
37310 W/System.err( 7350):     at com.lazy.library.logging.Logcat.saveLog2File(Logcat.java:560)
37311 W/System.err( 7350):     at com.lazy.library.logging.Logcat.saveLog2File(Logcat.java:511)
37312 W/System.err( 7350):     at com.lazy.library.logging.Logcat.fileLog(Logcat.java:884)
37313 W/System.err( 7350):     at com.lazy.library.logging.Logcat.access$000(Logcat.java:61)
37314 W/System.err( 7350):     at com.lazy.library.logging.Logcat$1.run(Logcat.java:728)
37315 W/System.err( 7350):     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
37316 W/System.err( 7350):     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
37317 W/System.err( 7350):     at java.lang.Thread.run(Thread.java:841)
37318 W/System.err( 7350): Caused by: libcore.io.ErrnoException: open failed: EMFILE (Too many open files)
37319 W/System.err( 7350):     at libcore.io.Posix.open(Native Method)
37320 W/System.err( 7350):     at libcore.io.BlockGuardOs.open(BlockGuardOs.java:110)
37321 W/System.err( 7350):     at libcore.io.IoBridge.open(IoBridge.java:393)
37322 W/System.err( 7350):     ... 10 more
37323 I/wpa_supplicant(  664): [CTRL_IFACE]wlan0: SIGNAL_POLL
37324 W/InputDispatcher(  483): channel '4246a9b0 Toast (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
37325 E/InputDispatcher(  483): channel '4246a9b0 Toast (server)' ~ Channel is unrecoverably broken and will be disposed!
37326 E/JavaBinder( 7350): !!! FAILED BINDER TRANSACTION !!!
37327 D/AndroidRuntime( 7350): Shutting down VM
